### ISSUE TITLE
Mapa deixa de funcionar despres d'utilitzar /e (Mode edició) i el /s per a guardar

### ISSUE THREAD

**Issue by Atm0n** [biels/Minicat#95]
Mapa deixa de funcionar despres d'utilitzar /e (Mode edició) i el /s per a guardar, un cop marxes del mapa editat(desconenctant tambe el mode edició) i guardat, quan hi vols tornar a accedir no pots fer-ho i produeix moltes excepcions a la consola.
He perdut un mapa ja, aixi que no l'utilitzeu sense estar segurs XD

**Comment by biels** [comment]
Si pots, enganxa aquestes excepcions de la consola

**Comment by Atm0n** [comment]
[13:14:01 INFO]: Preparing start region for level 1 (Seed: 1204907648209137132)
[13:14:01 ERROR]: Could not pass event InventoryClickEvent to BielAPI v2.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1889) [server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33) [server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10) [server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-3d850ec-809c399]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-3d850ec-809c399]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: net.minecraft.server.v1_12_R1.ReportedException: Loading NBT data
	at net.minecraft.server.v1_12_R1.NBTTagCompound.a(SourceFile:446) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTTagCompound.load(SourceFile:78) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTTagCompound.a(SourceFile:440) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTTagCompound.load(SourceFile:78) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:84) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:43) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.RegionFileCache.d(RegionFileCache.java:87) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:62) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:21) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:1) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:336) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.createWorld(CraftServer.java:946) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:454) ~[server.jar:git-Spigot-3d850ec-809c399]
	at com.biel.lobby.mapes.MapaResetejable.createVirtualWorld(MapaResetejable.java:82) ~[?:?]
	at com.biel.lobby.mapes.MapaResetejable.initialize(MapaResetejable.java:32) ~[?:?]
	at com.biel.lobby.mapes.Joc.initialize(Joc.java:101) ~[?:?]
	at com.biel.lobby.GestorMapes$ContenidorJoc.addMap(GestorMapes.java:255) ~[?:?]
	at com.biel.lobby.GestorMapes$ContenidorJoc.lambda$ObrirMenu$2(GestorMapes.java:383) ~[?:?]
	at com.biel.BielAPI.Utils.IconMenu.onInventoryClick(IconMenu.java:98) ~[?:?]
	at com.biel.BielAPI.events.EventBus.gameEvent(EventBus.java:358) ~[?:?]
	at com.biel.BielAPI.events.EventBus.recieveEvent(EventBus.java:68) ~[?:?]
	at com.biel.BielAPI.events.EventBusManager.recieveEvent(EventBusManager.java:22) ~[?:?]
	at com.biel.BielAPI.events.GeneralListener.h(GeneralListener.java:30) ~[?:?]
	at com.biel.BielAPI.events.GeneralListener.onInventoryClick(GeneralListener.java:178) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-3d850ec-809c399]
	... 15 more
Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240) ~[?:1.8.0_171]
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158) ~[?:1.8.0_171]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_171]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[?:1.8.0_171]
	at java.io.DataInputStream.readShort(DataInputStream.java:312) ~[?:1.8.0_171]
	at net.minecraft.server.v1_12_R1.NBTTagShort.load(SourceFile:31) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTTagList.load(SourceFile:66) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTTagCompound.a(SourceFile:440) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTTagCompound.load(SourceFile:78) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTTagCompound.a(SourceFile:440) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTTagCompound.load(SourceFile:78) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:84) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:53) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.NBTCompressedStreamTools.a(NBTCompressedStreamTools.java:43) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.RegionFileCache.d(RegionFileCache.java:87) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.ChunkRegionLoader.loadChunk(ChunkRegionLoader.java:62) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:21) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage1(ChunkIOProvider.java:1) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:336) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:137) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:120) ~[server.jar:git-Spigot-3d850ec-809c399]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:116) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.createWorld(CraftServer.java:946) ~[server.jar:git-Spigot-3d850ec-809c399]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:454) ~[server.jar:git-Spigot-3d850ec-809c399]
	at com.biel.lobby.mapes.MapaResetejable.createVirtualWorld(MapaResetejable.java:82) ~[?:?]
	at com.biel.lobby.mapes.MapaResetejable.initialize(MapaResetejable.java:32) ~[?:?]
	at com.biel.lobby.mapes.Joc.initialize(Joc.java:101) ~[?:?]
	at com.biel.lobby.GestorMapes$ContenidorJoc.addMap(GestorMapes.java:255) ~[?:?]
	at com.biel.lobby.GestorMapes$ContenidorJoc.lambda$ObrirMenu$2(GestorMapes.java:383) ~[?:?]
	at com.biel.BielAPI.Utils.IconMenu.onInventoryClick(IconMenu.java:98) ~[?:?]
	at com.biel.BielAPI.events.EventBus.gameEvent(EventBus.java:358) ~[?:?]
	at com.biel.BielAPI.events.EventBus.recieveEvent(EventBus.java:68) ~[?:?]
	at com.biel.BielAPI.events.EventBusManager.recieveEvent(EventBusManager.java:22) ~[?:?]
	at com.biel.BielAPI.events.GeneralListener.h(GeneralListener.java:30) ~[?:?]
	at com.biel.BielAPI.events.GeneralListener.onInventoryClick(GeneralListener.java:178) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-3d850ec-809c399]
	... 15 more

**Comment by biels** [comment]
No has iniciat la partida no abans d'entrar al mode edició? En quin mode de joc ha passat?

**Comment by Atm0n** [comment]
Batalla Aerea i si, era amb partida començada

**Comment by biels** [comment]
@Atm0n Val és això, el mode edició està pensat per ser utilitzat sense iniciar la partida
